services:
  - type: web
    name: gmrit-cse-teachers-day-2026
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: ADMIN_PIN
        sync: false
      - key: MONGODB_URI
        sync: false
